### PR TITLE
Stop interactive create or update on validation errors

### LINKED ISSUE #1348: Command `create` bypasses contract validations
Contracts are validated to ensure they are upgradeable (eg by checking they have no ctors) at `push` time. If they fail the validation, the push command fails. However, if the contract is never `push`ed manually, but is handled instead automatically during a `create`, then the warnings will be displayed **but the contract will be pushed and created anyway**.

We should halt the `create` process if a validation error is thrown.

### PR DESCRIPTION
**Pull request by spalladino**
The force flag was being passed to push from both create and upgrade to force pushing the implementation contracts. This caused the contracts to be pushed even if they had validation errors. This commit removes that flag so the create or upgrade fails if there are any errors.

Fixes #1348

### CODE REVIEW

File: packages/cli/src/commands/push.ts [hunk 1]
```diff
@@ -94,20 +91,9 @@ async function runActionIfRequested(externalOptions: any): Promise<void> {
...
-    if (
-      force ||
-      (!packageName && !networkFile.hasContract(contractAlias)) ||
-      (packageName && !networkFile.hasDependency(packageName))
-    ) {
-      await action({ ...options, dontExitProcess: true, skipTelemetry: true });
-    }
-  }
+  const { interactive } = options;
+  if (!interactive) return;
```
Comment (frangio) [inline packages/cli/src/commands/push.ts]: I personally prefer 1) avoiding early returns, and 2) always using braces. The latter should be a linter rule if we even agree to it, so I won't insist on it.

Comment (spalladino) [reply packages/cli/src/commands/push.ts]: 1) I like returns either at the beginning or the end, though not in the middle. Returns at the very first lines of the function feel natural as they are kind of "validations" of whether we want to run or not. Agree on avoiding them in the middle.

2) I particularly line single-line ifs when it's a return. Seems like we're on opposite sides on this one!

Comment (spalladino) [reply packages/cli/src/commands/push.ts]: Actually, just changed this so the return is on the very first line.
