### PR TITLE
Fixes for 2.8

### LINKED ISSUE #1468: `oz deploy` error: `A network name must be provided to execute the requested action.`
After setting up a new project with OpenZeppelin CLI and attempting a regular deploy, the following error is shown on `oz deploy`:
```
$ npx oz deploy
✓ Compiled contracts with solc 0.5.16 (commit.9c3226ce)
? Choose the kind of deployment regular
A network name must be provided to execute the requested action.
```
cli: `2.8.0-rc.1`
node: `v10.19.0`
npm: `6.13.7`
Operating System: `Windows 10 - WSL`
@truffle/hdwallet-provider: `1.0.31`

## networks.js
```
const { projectId, mnemonic } = require('./secrets.json');
const HDWalletProvider = require('@truffle/hdwallet-provider');

module.exports = {
  networks: {
    development: {
      protocol: 'http',
      host: 'localhost',
      port: 8545,
      gas: 5000000,
      gasPrice: 5e9,
      networkId: '*',
    },
    rinkeby: {
      provider: () => new HDWalletProvider(
        mnemonic, `https://rinkeby.infura.io/v3/${projectId}`
      ),
      networkId: 4,
      gasPrice: 10e9
    }
  },
};
```

Rerunning `npx oz deploy` succeeds:
```
$ npx oz deploy
Nothing to compile, all contracts are up to date.
? Choose the kind of deployment regular
? Pick a network development
? Pick a contract to deploy Box
0x67B5656d60a809915323Bf2C40A8bEF15A152e3e
```

### LINKED ISSUE #1470: Change call to action on `openzeppelin init` from `openzeppelin create` to `openzeppelin deploy`
After initializing OpenZeppelin, call to action is `openzeppelin create` this could be changed to `openzeppelin deploy`
```
$ npx oz init
? Welcome to the OpenZeppelin SDK! Choose a name for your project regdeploy
? Initial project version 1.0.0
Project initialized. Write a new contract in the contracts folder and run 'openzeppelin create' to deploy it.
```

cli: `2.8.0-rc.1`
node: `v10.19.0`
npm: `6.13.7`
Operating System: `Windows 10 - WSL`

### LINKED ISSUE #1471: Verify fails for regular deploy
Verify fails for regular deploy

```
$ npx oz verify
? Pick a network rinkeby
? Was your contract compiled with optimizations enabled? No
? Choose a remote endpoint etherscan
? Enter your Etherscan API key (get one at https://etherscan.io/myapikey) ZZZZMYAPIKEYZZZZ
? Pick a contract to verify Box
Contract Box not found in this project
```

cli: `2.8.0-rc.1`
node: `v10.19.0`
npm: `6.13.7`
Operating System: `Windows 10 - WSL`

### PR DESCRIPTION
**Pull request by frangio**
Fixes #1470.
Fixes #1471.
Fixes #1468.

### CODE REVIEW

File: packages/cli/src/commands/deploy/spec.ts [hunk 1]
```diff
@@ -108,7 +108,7 @@ export const options: Option[] = [
       const networks = ConfigManager.getNetworkNamesFromConfig();
       const { network: lastNetwork, expired } = Session.getNetwork();
 
-      if (expired) {
+      if (expired || lastNetwork === undefined) {
```
Comment (spalladino) [inline packages/cli/src/commands/deploy/spec.ts]: This should be ported to verify as well

**Comment by spalladino** [comment]
I'm worried that none of these fixes has any tests. If we are considering migrating all commands to the new spec format, then we need to add tests for this layer, as we do with the current version. Also, for the future, let's split fixes for different issues into different PRs, even if they are small.

**Comment by spalladino** [comment]
Cherry-picked to 2.8
